# Generated by Django 4.2.3 on 2023-08-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('altName', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
                ('dunker', models.CharField(blank=True, max_length=75, null=True)),
                ('hierarchy', models.CharField(blank=True, max_length=250, null=True)),
                ('prereq', models.CharField(blank=True, max_length=150, null=True)),
                ('classification', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'dunks',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('altName', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('video', models.CharField(blank=True, max_length=500, null=True)),
                ('dunker', models.CharField(blank=True, max_length=75, null=True)),
                ('hierarchy', models.CharField(blank=True, max_length=250, null=True)),
                ('prereq', models.CharField(blank=True, max_length=150, null=True)),
                ('classification', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'passes',
            },
        ),
    ]
